### PR TITLE
add UTF-8 fonts compatibility

### PR DESCRIPTION
**Pull request by mayabushlyakova**
This small fix will allow to use UTF-8 fonts. 

Maybe i will add some of my utf-8 fonts later...

### CODE REVIEW

**Comment by pljakobs** [comment]
UTF-8 fonts don't lend themselves easily to small memory applications as many of them have non-contiguous glyph tables.
Nevertheless, i18n is important for me, too, but I would suggest that character sets following iso-8859-x would be the better approach as that would keep it to 255 characters per font.

**Comment by Tijgerd** [comment]
maby you can add an:  #if defined(SUPPORT_UTF8)

**Comment by idea--list** [comment]
I do not think iso-8859-x would be a good idea. Simply because that is an even bigger pitfall than good old ASCII. I mean if you can just use ASCII you know what you may expect. Choosing ISO now would just pave the way to hell and make porting to UTF-8 at some point even harder.

I agree with @Tijgerd and UTF-8 should be an opt-in turned off by default but commented properly.

**Comment by PaintYourDragon** [comment]
Thank you for the contribution. Will be closing this PR and studying #200 which incorporates a similar change and takes it a step further.

**Pull request closed without merging**
