### PR TITLE
Added display scrolling ability

### PR DESCRIPTION
**Pull request by agprimatic**
Added a new flag called scroll.  If this is set by the function setTextScroll().  If scroll is set and the cursor is moved beyond the bottom of the display, the contents are scrolled up and the bottom line cleared (code added to write()). This allows traditional scrolling to occur when text is written that would otherwise be located beyond the bottom of the screen.

This change also adds the function dispCopy(), which provides a method to copy a part of the display, starting at (x0,y0) and going to (h,w) to a new location (x1,y1) on the screen. By default, it performs a pixel-by-pixel copy, but it can be overloaded if there is a faster way to perform the copy.

### CODE REVIEW

**Comment by hulkco** [comment]
Hi agprimatic you can put some samples that use the setTextScroll() funtion?
Thanks

**Comment by agprimatic** [comment]
Wow, lots of changes in this repository since last October.  I pulled the latest code and will merge my changes into it. There are also updates to Adafruit_SSD1306 to support scrolling.
Finally, I have a short example file that I will put into Adafruit_SSD1306/examples.

**Comment by jonblack** [comment]
Is there a reason why this or #76 haven't been merged yet?

**Comment by tablatronix** [comment]
@agprimatic resolve conflicts ?

**Comment by tablatronix** [comment]
ssd1306 pr ref
https://github.com/adafruit/Adafruit_SSD1306/pull/64

**Comment by tablatronix** [comment]
complaining about missing file
`#include "gfxfont.h"`

**Comment by tablatronix** [comment]
I think your merge is failed to `add` gfxfont.h missing still

**Comment by agprimatic** [comment]
I think my repository is now up to date with the latest from adafruit.  Should I create a new pull request?

**Comment by j-lang** [comment]
would be great, if ith pull request could be finished

**Comment by PaintYourDragon** [comment]
Making a sweep through some old PRs. Always grateful for contributions, but decided against merging this, since not all display hardware has pixel-get capability and making getPixel() virtual will cause mayhem with every display subclass (there’s a lot now). Forks are welcome and encouraged for special features for your own needs, upstream changes can then be kept in sync. Thank you.

**Pull request closed without merging**
