### PR TITLE
Fix warnings "comparison between signed and unsigned integer expressi…

### PR DESCRIPTION
**Pull request by FrankBoesing**
…ons "

Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be aware we have many GitHub repositories to manage and
can't immediately respond to every request.  There is no need to bump or check in
on a pull request (it will clutter the discussion of the request).

Also don't be worried if the request is closed or not integrated--sometimes the
priorities of Adafruit's GitHub code (education, ease of use) might not match the
priorities of the pull request.  Don't fret, the open source community thrives on
forks and GitHub makes it easy to keep your changes in a forked repo.

After reviewing the guidelines above you can delete this text from the pull request.

### CODE REVIEW

**Comment by FrankBoesing** [comment]
Ok, abviuosly Adafruit is not interesting in fixing warnings.

Closing here.

**Comment by dhalbert** [comment]
We are interested. Please leave open, and we'll keep this for the future.

**Comment by ladyada** [comment]
@FrankBoesing we have 1400 open source repositories, so not every PR gets priority - we prioritize bug fixes and non-conflict PRs

**Comment by bxparks** [comment]
I think both of these compiler warnings were fixed in 6c648c6d on Sat Nov 21 09:11:50 2020 -0800, so I think this can be closed.

@ladyada: Sympathize with the struggle to keep up with maintenance work. On the other hand, when I see a project with 53 open PR requests, it does discourage me from sending any fixes for that project. I see 7 `-Wunused-parameter` warnings in `Adafruit_SPITFT.cpp`, `Adafruit_GFX.cpp`, and  `Adafruit_PCD8544.cpp`. It would be great to fix those so that I can keep a clean build in my app. Should I send a PR for those? Or are all all too overloaded, so I shouldn't waste your time or my time?

**Comment by ladyada** [comment]
We merge polite, simple, non-conflicting, documented fixes first - https://github.com/adafruit/Adafruit-GFX-Library/pulls?q=is%3Apr+is%3Aclosed and we merge PRs all the time. 

We prioritize ones that are not likely to break behavior for the thousands of users and do not require hand-fixing of conflicts. Many PRs are well meaning and can create problems that were not expected by the author :)

**Comment by FrankBoesing** [comment]
No Problem, but nobody can forsee that a later PR(17 days old) that got merged addresses the same issue.

**Pull request closed without merging**
