### PR TITLE
(almost) stand-alone executable to create fonts

### PR DESCRIPTION
**Pull request by johnbacas**
1. Unzip folder
2. Put inside folder the .ttf file you want to convert
3. Open command prompt and use -cd- commands to reach folder
4. Use the command:  fontconvert  afont.ttf  **x** >  afont**x**pt7b.h    (where x is the font size eg 9,12)
5. Enjoy

### CODE REVIEW

**Comment by Protonerd** [comment]
Thumbs up johnbacas, great work on helping out poor Win users like myself, grateful forever!

**Comment by Waged** [comment]
hello, I'm using macOS and fontconvert is not a command in my situation , anyway to run this command ? thanks :)

**Comment by pljakobs** [comment]
Hi Waged, you will have to install Freetype 2 including the devel packages on your platform. Since I don't know the mac platform, I'll have to refer you to [freetype.org](https://www.freetype.org) if your system does not have a package manager similar to yum or apt that would provide you a set of open source packages.

**Comment by Waged** [comment]
Hi pljakobs , actually freetype is preinstalled in MacOs and also I've installed Xcode which said that it comes with freetype as well , there's no issues of having it.. 
the problem is that I've no procedures to do it and reach to the .h file from the .ttf  format... 
if anyone knows  really I'll be grateful.. 
thanks,

**Comment by Waged** [comment]
hi, I've faced the same problem to create the .h file from .ttf file , I'm using MacOS  
after trials i made  this procedures and it works 👍 
1- install brew: link :http://macappstore.org/freetype/
2-install freetype2 link : https://opensource.ncsa.illinois.edu/confluence/pages/viewpage.action?pageId=61604031 
3- run command : make fontconvert
4- after downloading the .ttf file  and putting it inside the fonconvert folder run command:
./fontconvert Orgy.ttf  18  > Orgy18.h

**Comment by pljakobs** [comment]
thanks Waged, yes, it's always a bit of a mistery how different platforms want the build environment configured, especially when using proprietary compilers.
Thanks for the update. I'm glad the tool is in fact totally portable ;-)

**Comment by PaintYourDragon** [comment]
Making a sweep through some old PRs. The gesture is much appreciated, but we generally avoid having outside-compiled binary executables in repos. Thank you.

**Pull request closed without merging**
